"""initial schema

Revision ID: 3b3c8ce72c1b
Revises: 
Create Date: 2026-08-03 23:07:04.171096
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Кросс-диалектные типы (GUID / JSONB / Money / TZDateTime) рендерятся
# автогенерацией с полным путем, поэтому модуль импортируется всегда.
import tco.db.base


revision: str = '3b3c8ce72c1b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('actor_user_id', sa.String(length=64), nullable=True),
    sa.Column('actor_username', sa.String(length=64), nullable=True),
    sa.Column('actor_role', sa.String(length=16), nullable=True),
    sa.Column('object_type', sa.String(length=48), nullable=True),
    sa.Column('object_id', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.String(length=1024), nullable=True),
    sa.Column('payload', tco.db.base.JSONB(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', tco.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('id', tco.db.base.GUID(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_actor', 'audit_events', ['actor_username', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index('ix_audit_object', 'audit_events', ['object_type', 'object_id'], unique=False)
    op.create_index('ix_audit_time', 'audit_events', ['created_at'], unique=False)
    op.create_table('calculation_profiles',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('version_seq', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('rules', tco.db.base.JSONB(), nullable=False),
    sa.Column('activated_at', tco.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('archived_at', tco.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('id', tco.db.base.GUID(length=36), nullable=False),
    sa.Column('created_at', tco.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', tco.db.base.TZDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'version', name='uq_profile_code_version')
    )
    op.create_index(op.f('ix_calculation_profiles_created_at'), 'calculation_profiles', ['created_at'], unique=False)
    op.create_index('ix_profiles_status', 'calculation_profiles', ['status'], unique=False)
    op.create_table('cities',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('name_en', sa.String(length=128), nullable=True),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('iata_codes', tco.db.base.JSONB(), nullable=False),
    sa.Column('rail_station_codes', tco.db.base.JSONB(), nullable=False),
    sa.Column('source_ids', tco.db.base.JSONB(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('supports_avia', sa.Boolean(), nullable=False),
    sa.Column('supports_rail', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', tco.db.base.GUID(length=36), nullable=False),
    sa.Column('created_at', tco.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', tco.db.base.TZDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_cities_code')
    )
    op.create_index('ix_cities_active', 'cities', ['is_active'], unique=False)
    op.create_index(op.f('ix_cities_created_at'), 'cities', ['created_at'], unique=False)
    op.create_table('result_cache',
    sa.Column('cache_key', sa.String(length=128), nullable=False),
    sa.Column('scenario_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('market_snapshot_id', tco.db.base.GUID(length=36), nullable=True),
    sa.Column('scenario_run_id', tco.db.base.GUID(length=36), nullable=True),
    sa.Column('profile_version', sa.String(length=32), nullable=False),
    sa.Column('expires_at', tco.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('payload', tco.db.base.JSONB(), nullable=False),
    sa.Column('id', tco.db.base.GUID(length=36), nullable=False),
    sa.Column('created_at', tco.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', tco.db.base.TZDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key', name='uq_result_cache_key')
    )
    op.create_index(op.f('ix_result_cache_created_at'), 'result_cache', ['created_at'], unique=False)
    op.create_index('ix_result_cache_expires', 'result_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_result_cache_scenario_fingerprint'), 'result_cache', ['scenario_fingerprint'], unique=False)
    op.create_table('scenario_templates',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('defaults', tco.db.base.JSONB(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', tco.db.base.GUID(length=36), nullable=False),
    sa.Column('created_at', tco.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', tco.db.base.TZDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_scenario_templates_code')
    )
    op.create_index(op.f('ix_scenario_templates_created_at'), 'scenario_templates', ['created_at'], unique=False)
    op.create_table('sources',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('protocol', sa.String(length=16), nullable=False),
    sa.Column('offer_types', tco.db.base.JSONB(), nullable=False),
    sa.Column('qualification_status', sa.String(length=16), nullable=False),
    sa.Column('qualification_notes', sa.String(length=4096), nullable=True),
    sa.Column('qualified_at', tco.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('requires_credentials', sa.Boolean(), nullable=False),
    sa.Column('allowed_hosts', tco.db.base.JSONB(), nullable=False),
    sa.Column('legal_status', sa.String(length=64), nullable=True),
    sa.Column('storage_allowed', sa.Boolean(), nullable=False),
    sa.Column('html_storage_allowed', sa.Boolean(), nullable=False),
    sa.Column('min_supported_date', sa.Date(), nullable=True),
    sa.Column('max_supported_date', sa.Date(), nullable=True),
    sa.Column('booking_horizon_days', sa.Integer(), nullable=True),
    sa.Column('horizon_checked_at', tco.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('supported_city_codes', tco.db.base.JSONB(), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=True),
    sa.Column('connector_version', sa.String(length=32), nullable=False),
    sa.Column('config', tco.db.base.JSONB(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('circuit_open_until', tco.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', tco.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', tco.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=1024), nullable=True),
    sa.Column('id', tco.db.base.GUID(length=36), nullable=False),
    sa.Column('created_at', tco.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', tco.db.base.TZDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_sources_code')
    )
    op.create_index('ix_sources_category_enabled', 'sources', ['category', 'is_enabled'], unique=False)
    op.create_index(op.f('ix_sources_created_at'), 'sources', ['created_at'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', tco.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('id', tco.db.base.GUID(length=36), nullable=False),
    sa.Column('created_at', tco.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', tco.db.base.TZDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', name='uq_users_username')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_table('source_confidence',
    sa.Column('source_id', tco.db.base.GUID(length=36), nullable=False),
    sa.Column('calculation_date', sa.Date(), nullable=False),
    sa.Column('formula_version', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('input_metrics', tco.db.base.JSONB(), nullable=False),
    sa.Column('factor_scores', tco.db.base.JSONB(), nullable=False),
    sa.Column('manual_override', sa.Float(), nullable=True),
    sa.Column('override_reason', sa.String(length=1024), nullable=True),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('overridden_at', tco.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('created_at', tco.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('id', tco.db.base.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'calculation_date', name='uq_source_confidence_day')
    )
    op.create_index(op.f('ix_source_confidence_created_at'), 'source_confidence', ['created_at'], unique=False)
    op.create_index('ix_source_confidence_source', 'source_confidence', ['source_id', 'calculation_date'], unique=False)
    op.create_table('travel_scenarios',
    sa.Column('code', sa.String(length=96), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scenario_type', sa.String(length=16), nullable=False),
    sa.Column('origin_city_id', tco.db.base.GUID(length=36), nullable=False),
    sa.Column('destination_city_id', tco.db.base.GUID(length=36), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('nights', sa.Integer(), nullable=False),
    sa.Column('adults', sa.Integer(), nullable=False),
    sa.Column('children_ages', tco.db.base.JSONB(), nullable=False),
    sa.Column('transport_type', sa.String(length=8), nullable=False),
    sa.Column('flight_fare_type', sa.String(length=24), nullable=True),
    sa.Column('rail_class', sa.String(length=24), nullable=True),
    sa.Column('accommodation_type', sa.String(length=24), nullable=False),
    sa.Column('stars', sa.String(length=16), nullable=False),
    sa.Column('meal_type', sa.String(length=16), nullable=False),
    sa.Column('cancellation_filter', sa.String(length=24), nullable=False),
    sa.Column('calculation_profile_id', tco.db.base.GUID(length=36), nullable=True),
    sa.Column('active_from', sa.Date(), nullable=True),
    sa.Column('active_until', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', tco.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('tags', tco.db.base.JSONB(), nullable=False),
    sa.Column('notes', sa.String(length=2048), nullable=True),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('id', tco.db.base.GUID(length=36), nullable=False),
    sa.Column('created_at', tco.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', tco.db.base.TZDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['calculation_profile_id'], ['calculation_profiles.id'], ),
    sa.ForeignKeyConstraint(['destination_city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['origin_city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_travel_scenarios_code')
    )
    op.create_index('ix_scenarios_active_type', 'travel_scenarios', ['is_active', 'scenario_type'], unique=False)
    op.create_index('ix_scenarios_departure', 'travel_scenarios', ['departure_date'], unique=False)
    op.create_index('ix_scenarios_fingerprint', 'travel_scenarios', ['fingerprint'], unique=False)
    op.create_index('ix_scenarios_route', 'travel_scenarios', ['origin_city_id', 'destination_city_id'], unique=False)
    op.create_index(op.f('ix_travel_scenarios_created_at'), 'travel_scenarios', ['created_at'], unique=False)
    op.create_table('jobs',
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('idempotency_key', sa.String(length=96), nullable=False),
    sa.Column('scenario_id', tco.db.base.GUID(length=36), nullable=True),
    sa.Column('market_snapshot_id', tco.db.base.GUID(length=36), nullable=True),
    sa.Column('scenario_run_id', tco.db.base.GUID(length=36), nullable=True),
    sa.Column('parent_job_id', tco.db.base.GUID(length=36), nullable=True),
    sa.Column('celery_task_id', sa.String(length=64), nullable=True),
    sa.Column('queue', sa.String(length=64), nullable=True),
    sa.Column('params', tco.db.base.JSONB(), nullable=False),
    sa.Column('result', tco.db.base.JSONB(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=4096), nullable=True),
    sa.Column('progress_current', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('progress_message', sa.String(length=512), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('queued_at', tco.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('started_at', tco.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', tco.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', tco.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', tco.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', tco.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('id', tco.db.base.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['parent_job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['travel_scenarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_jobs_idempotency')
    )
    op.create_index(op.f('ix_jobs_celery_task_id'), 'jobs', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_jobs_correlation_id'), 'jobs', ['correlation_id'], unique=False)
    op.create_index('ix_jobs_created', 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_heartbeat_at'), 'jobs', ['heartbeat_at'], unique=False)
    op.create_index('ix_jobs_parent', 'jobs', ['parent_job_id'], unique=False)
    op.create_index('ix_jobs_scenario', 'jobs', ['scenario_id'], unique=False)
    op.create_index('ix_jobs_status_type', 'jobs', ['status', 'job_type'], unique=False)
    op.create_table('market_snapshots',
    sa.Column('scenario_id', tco.db.base.GUID(length=36), nullable=False),
    sa.Column('scenario_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('snapshot_type', sa.String(length=24), nullable=False),
    sa.Column('requested_at', tco.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('completed_at', tco.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('observed_at', tco.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('observation_slot', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_ids', tco.db.base.JSONB(), nullable=False),
    sa.Column('source_codes', tco.db.base.JSONB(), nullable=False),
    sa.Column('transport_offer_count', sa.Integer(), nullable=False),
    sa.Column('accommodation_offer_count', sa.Integer(), nullable=False),
    sa.Column('valid_offer_count', sa.Integer(), nullable=False),
    sa.Column('invalid_offer_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_offer_count', sa.Integer(), nullable=False),
    sa.Column('outlier_offer_count', sa.Integer(), nullable=False),
    sa.Column('raw_response_refs', tco.db.base.JSONB(), nullable=False),
    sa.Column('html_snapshot_refs', tco.db.base.JSONB(), nullable=False),
    sa.Column('normalization_version', sa.String(length=32), nullable=False),
    sa.Column('connector_versions', tco.db.base.JSONB(), nullable=False),
    sa.Column('source_confidence_summary', tco.db.base.JSONB(), nullable=False),
    sa.Column('collection_summary', tco.db.base.JSONB(), nullable=False),
    sa.Column('scenario_params', tco.db.base.JSONB(), nullable=False),
    sa.Column('error_summary', tco.db.base.JSONB(), nullable=False),
    sa.Column('contains_synthetic_data', sa.Boolean(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('job_id', tco.db.base.GUID(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', tco.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('offers_purged_at', tco.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('id', tco.db.base.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['travel_scenarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_market_snapshots_idempotency')
    )
    op.create_index(op.f('ix_market_snapshots_created_at'), 'market_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_market_snapshots_scenario_fingerprint'), 'market_snapshots', ['scenario_fingerprint'], unique=False)
    op.create_index('ix_snapshots_observation_date', 'market_snapshots', ['observation_date'], unique=False)
    op.create_index('ix_snapshots_scenario_time', 'market_snapshots', ['scenario_id', 'observed_at'], unique=False)
    op.create_index('ix_snapshots_type_status', 'market_snapshots', ['snapshot_type', 'status'], unique=False)
    op.create_table('export_artifacts',
    sa.Column('job_id', tco.db.base.GUID(length=36), nullable=False),
    sa.Column('dataset', sa.String(length=32), nullable=False),
    sa.Column('export_format', sa.String(length=8), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_ref', sa.String(length=1024), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('filters', tco.db.base.JSONB(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', tco.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', tco.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('id', tco.db.base.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exports_job', 'export_artifacts', ['job_id'], unique=False)
    op.create_table('job_events',
    sa.Column('job_id', tco.db.base.GUID(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('message', sa.String(length=2048), nullable=True),
    sa.Column('payload', tco.db.base.JSONB(), nullable=False),
    sa.Column('created_at', tco.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('id', tco.db.base.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_events_job_time', 'job_events', ['job_id', 'created_at'], unique=False)
    op.create_table('raw_responses',
    sa.Column('market_snapshot_id', tco.db.base.GUID(length=36), nullable=True),
    sa.Column('scenario_id', tco.db.base.GUID(length=36), nullable=True),
    sa.Column('source_id', tco.db.base.GUID(length=36), nullable=False),
    sa.Column('source_code', sa.String(length=64), nullable=False),
    sa.Column('offer_type', sa.String(length=24), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('request_params', tco.db.base.JSONB(), nullable=False),
    sa.Column('endpoint', sa.String(length=512), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('storage_ref', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('content_encoding', sa.String(length=32), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('collected_at', tco.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', tco.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('is_purged', sa.Boolean(), nullable=False),
    sa.Column('connector_version', sa.String(length=32), nullable=True),
    sa.Column('id', tco.db.base.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['market_snapshot_id'], ['market_snapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scenario_id'], ['travel_scenarios.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_responses_collected_at'), 'raw_responses', ['collected_at'], unique=False)
    op.create_index('ix_raw_responses_expires', 'raw_responses', ['expires_at'], unique=False)
    op.create_index('ix_raw_responses_snapshot', 'raw_responses', ['market_snapshot_id'], unique=False)
    op.create_index('ix_raw_responses_source_time', 'raw_responses', ['source_id', 'collected_at'], unique=False)
    op.create_table('scenario_runs',
    sa.Column('scenario_id', tco.db.base.GUID(length=36), nullable=False),
    sa.Column('market_snapshot_id', tco.db.base.GUID(length=36), nullable=True),
    sa.Column('run_type', sa.String(length=16), nullable=False),
    sa.Column('started_at', tco.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('completed_at', tco.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('profile_id', tco.db.base.GUID(length=36), nullable=False),
    sa.Column('profile_code', sa.String(length=64), nullable=False),
    sa.Column('profile_version', sa.String(length=32), nullable=False),
    sa.Column('normalization_version', sa.String(length=32), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('component_statuses', tco.db.base.JSONB(), nullable=False),
    sa.Column('transport_p25', tco.db.base.Money(precision=14, scale=2), nullable=True),
    sa.Column('transport_median', tco.db.base.Money(precision=14, scale=2), nullable=True),
    sa.Column('transport_p75', tco.db.base.Money(precision=14, scale=2), nullable=True),
    sa.Column('transport_source_count', sa.Integer(), nullable=False),
    sa.Column('transport_offer_count', sa.Integer(), nullable=False),
    sa.Column('transport_disagreement', sa.Float(), nullable=True),
    sa.Column('hotel_p25', tco.db.base.Money(precision=14, scale=2), nullable=True),
    sa.Column('hotel_median', tco.db.base.Money(precision=14, scale=2), nullable=True),
    sa.Column('hotel_p75', tco.db.base.Money(precision=14, scale=2), nullable=True),
    sa.Column('hotel_source_count', sa.Integer(), nullable=False),
    sa.Column('hotel_offer_count', sa.Integer(), nullable=False),
    sa.Column('hotel_disagreement', sa.Float(), nullable=True),
    sa.Column('total_estimated_cost', tco.db.base.Money(precision=14, scale=2), nullable=True),
    sa.Column('total_p25', tco.db.base.Money(precision=14, scale=2), nullable=True),
    sa.Column('total_p75', tco.db.base.Money(precision=14, scale=2), nullable=True),
    sa.Column('price_per_person', tco.db.base.Money(precision=14, scale=2), nullable=True),
    sa.Column('transport_share', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('traveler_count', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('quality_breakdown', tco.db.base.JSONB(), nullable=False),
    sa.Column('confidence_level', sa.String(length=16), nullable=True),
    sa.Column('confidence_reason', sa.String(length=1024), nullable=True),
    sa.Column('confidence_factors', tco.db.base.JSONB(), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('source_codes', tco.db.base.JSONB(), nullable=False),
    sa.Column('valid_offer_count', sa.Integer(), nullable=False),
    sa.Column('excluded_offer_count', sa.Integer(), nullable=False),
    sa.Column('outlier_offer_count', sa.Integer(), nullable=False),
    sa.Column('explainability_payload', tco.db.base.JSONB(), nullable=False),
    sa.Column('source_breakdown', tco.db.base.JSONB(), nullable=False),
    sa.Column('cache_key', sa.String(length=128), nullable=True),
    sa.Column('served_from_cache', sa.Boolean(), nullable=False),
    sa.Column('contains_synthetic_data', sa.Boolean(), nullable=False),
    sa.Column('error_summary', tco.db.base.JSONB(), nullable=False),
    sa.Column('job_id', tco.db.base.GUID(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', tco.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('id', tco.db.base.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['market_snapshot_id'], ['market_snapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['calculation_profiles.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['travel_scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_runs_cache_key', 'scenario_runs', ['cache_key'], unique=False)
    op.create_index('ix_runs_observation_date', 'scenario_runs', ['observation_date'], unique=False)
    op.create_index('ix_runs_scenario_time', 'scenario_runs', ['scenario_id', 'started_at'], unique=False)
    op.create_index('ix_runs_snapshot', 'scenario_runs', ['market_snapshot_id'], unique=False)
    op.create_index('ix_runs_status_type', 'scenario_runs', ['status', 'run_type'], unique=False)
    op.create_index(op.f('ix_scenario_runs_created_at'), 'scenario_runs', ['created_at'], unique=False)
    op.create_table('snapshot_source_results',
    sa.Column('market_snapshot_id', tco.db.base.GUID(length=36), nullable=False),
    sa.Column('source_id', tco.db.base.GUID(length=36), nullable=False),
    sa.Column('source_code', sa.String(length=64), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('offer_type', sa.String(length=24), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('outcome', sa.String(length=24), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('raw_offer_count', sa.Integer(), nullable=False),
    sa.Column('normalized_offer_count', sa.Integer(), nullable=False),
    sa.Column('valid_offer_count', sa.Integer(), nullable=False),
    sa.Column('invalid_offer_count', sa.Integer(), nullable=False),
    sa.Column('unclassified_offer_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_offer_count', sa.Integer(), nullable=False),
    sa.Column('required_field_completeness', sa.Float(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('connector_version', sa.String(length=32), nullable=True),
    sa.Column('collected_at', tco.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('id', tco.db.base.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['market_snapshot_id'], ['market_snapshots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_snapshot_id', 'source_id', 'offer_type', name='uq_snapshot_source_offer_type')
    )
    op.create_index('ix_snapshot_source_results_snapshot', 'snapshot_source_results', ['market_snapshot_id'], unique=False)
    op.create_table('source_metrics',
    sa.Column('source_id', tco.db.base.GUID(length=36), nullable=False),
    sa.Column('market_snapshot_id', tco.db.base.GUID(length=36), nullable=True),
    sa.Column('scenario_id', tco.db.base.GUID(length=36), nullable=True),
    sa.Column('offer_type', sa.String(length=24), nullable=False),
    sa.Column('observed_at', tco.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('outcome', sa.String(length=24), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('raw_offer_count', sa.Integer(), nullable=False),
    sa.Column('normalized_offer_count', sa.Integer(), nullable=False),
    sa.Column('valid_offer_count', sa.Integer(), nullable=False),
    sa.Column('invalid_offer_count', sa.Integer(), nullable=False),
    sa.Column('unclassified_offer_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_offer_count', sa.Integer(), nullable=False),
    sa.Column('outlier_offer_count', sa.Integer(), nullable=False),
    sa.Column('required_field_completeness', sa.Float(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('connector_version', sa.String(length=32), nullable=True),
    sa.Column('id', tco.db.base.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['market_snapshot_id'], ['market_snapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scenario_id'], ['travel_scenarios.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_metrics_observed_at'), 'source_metrics', ['observed_at'], unique=False)
    op.create_index('ix_source_metrics_snapshot', 'source_metrics', ['market_snapshot_id'], unique=False)
    op.create_index('ix_source_metrics_source_time', 'source_metrics', ['source_id', 'observed_at'], unique=False)
    op.create_table('html_snapshots',
    sa.Column('market_snapshot_id', tco.db.base.GUID(length=36), nullable=True),
    sa.Column('raw_response_id', tco.db.base.GUID(length=36), nullable=True),
    sa.Column('source_id', tco.db.base.GUID(length=36), nullable=False),
    sa.Column('source_code', sa.String(length=64), nullable=False),
    sa.Column('scenario_id', tco.db.base.GUID(length=36), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('final_url', sa.String(length=2048), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('response_headers', tco.db.base.JSONB(), nullable=False),
    sa.Column('storage_ref', sa.String(length=1024), nullable=False),
    sa.Column('screenshot_ref', sa.String(length=1024), nullable=True),
    sa.Column('extraction_log', tco.db.base.JSONB(), nullable=False),
    sa.Column('parser_version', sa.String(length=32), nullable=True),
    sa.Column('content_encoding', sa.String(length=32), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('collected_at', tco.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', tco.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('is_purged', sa.Boolean(), nullable=False),
    sa.Column('id', tco.db.base.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['market_snapshot_id'], ['market_snapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['raw_response_id'], ['raw_responses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scenario_id'], ['travel_scenarios.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_html_snapshots_collected_at'), 'html_snapshots', ['collected_at'], unique=False)
    op.create_index('ix_html_snapshots_expires', 'html_snapshots', ['expires_at'], unique=False)
    op.create_index('ix_html_snapshots_snapshot', 'html_snapshots', ['market_snapshot_id'], unique=False)
    op.create_table('offers',
    sa.Column('market_snapshot_id', tco.db.base.GUID(length=36), nullable=False),
    sa.Column('scenario_id', tco.db.base.GUID(length=36), nullable=True),
    sa.Column('source_id', tco.db.base.GUID(length=36), nullable=False),
    sa.Column('source_code', sa.String(length=64), nullable=False),
    sa.Column('source_offer_id', sa.String(length=255), nullable=True),
    sa.Column('offer_type', sa.String(length=24), nullable=False),
    sa.Column('collected_at', tco.db.base.TZDateTime(timezone=True), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total_price', tco.db.base.Money(precision=14, scale=2), nullable=True),
    sa.Column('price_per_night', tco.db.base.Money(precision=14, scale=2), nullable=True),
    sa.Column('validity_status', sa.String(length=32), nullable=False),
    sa.Column('classification_status', sa.String(length=32), nullable=False),
    sa.Column('validation_messages', tco.db.base.JSONB(), nullable=False),
    sa.Column('technical_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('equivalence_key', sa.String(length=128), nullable=True),
    sa.Column('equivalence_group_id', tco.db.base.GUID(length=36), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('is_outlier', sa.Boolean(), nullable=False),
    sa.Column('matches_profile', sa.Boolean(), nullable=False),
    sa.Column('exclusion_reason', sa.String(length=32), nullable=False),
    sa.Column('exclusion_detail', sa.String(length=512), nullable=True),
    sa.Column('raw_object_ref', sa.String(length=1024), nullable=True),
    sa.Column('raw_response_id', tco.db.base.GUID(length=36), nullable=True),
    sa.Column('html_snapshot_id', tco.db.base.GUID(length=36), nullable=True),
    sa.Column('deeplink', sa.String(length=2048), nullable=True),
    sa.Column('normalization_version', sa.String(length=32), nullable=False),
    sa.Column('connector_version', sa.String(length=32), nullable=True),
    sa.Column('source_metadata', tco.db.base.JSONB(), nullable=False),
    sa.Column('id', tco.db.base.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['html_snapshot_id'], ['html_snapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['market_snapshot_id'], ['market_snapshots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_response_id'], ['raw_responses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scenario_id'], ['travel_scenarios.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_offers_collected', 'offers', ['collected_at'], unique=False)
    op.create_index('ix_offers_equivalence', 'offers', ['equivalence_group_id'], unique=False)
    op.create_index('ix_offers_fingerprint', 'offers', ['market_snapshot_id', 'technical_fingerprint'], unique=False)
    op.create_index('ix_offers_snapshot_source', 'offers', ['market_snapshot_id', 'source_id'], unique=False)
    op.create_index('ix_offers_snapshot_type', 'offers', ['market_snapshot_id', 'offer_type'], unique=False)
    op.create_table('accommodation_offers',
    sa.Column('offer_id', tco.db.base.GUID(length=36), nullable=False),
    sa.Column('property_source_id', sa.String(length=128), nullable=True),
    sa.Column('property_name', sa.String(length=512), nullable=True),
    sa.Column('property_key', sa.String(length=256), nullable=True),
    sa.Column('accommodation_type', sa.String(length=24), nullable=False),
    sa.Column('accommodation_type_raw', sa.String(length=128), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('stars_status', sa.String(length=24), nullable=False),
    sa.Column('address', sa.String(length=1024), nullable=True),
    sa.Column('city_name', sa.String(length=128), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('check_in', sa.Date(), nullable=True),
    sa.Column('check_out', sa.Date(), nullable=True),
    sa.Column('nights', sa.Integer(), nullable=True),
    sa.Column('room_name', sa.String(length=512), nullable=True),
    sa.Column('room_count', sa.Integer(), nullable=False),
    sa.Column('max_guests', sa.Integer(), nullable=True),
    sa.Column('capacity_confirmed', sa.Boolean(), nullable=False),
    sa.Column('capacity_confirmation_basis', sa.String(length=64), nullable=True),
    sa.Column('adults', sa.Integer(), nullable=True),
    sa.Column('children_ages', tco.db.base.JSONB(), nullable=False),
    sa.Column('meal_type', sa.String(length=16), nullable=False),
    sa.Column('meal_raw', sa.String(length=255), nullable=True),
    sa.Column('cancellation_type', sa.String(length=24), nullable=False),
    sa.Column('cancellation_raw', sa.String(length=512), nullable=True),
    sa.Column('review_score', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('amenities', tco.db.base.JSONB(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('offer_id')
    )
    op.create_index('ix_accommodation_property_key', 'accommodation_offers', ['property_key'], unique=False)
    op.create_table('flight_offers',
    sa.Column('offer_id', tco.db.base.GUID(length=36), nullable=False),
    sa.Column('origin_code', sa.String(length=8), nullable=True),
    sa.Column('destination_code', sa.String(length=8), nullable=True),
    sa.Column('origin_name', sa.String(length=255), nullable=True),
    sa.Column('destination_name', sa.String(length=255), nullable=True),
    sa.Column('outbound_departure_at', tco.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('outbound_arrival_at', tco.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('inbound_departure_at', tco.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('inbound_arrival_at', tco.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('outbound_segments', tco.db.base.JSONB(), nullable=False),
    sa.Column('inbound_segments', tco.db.base.JSONB(), nullable=False),
    sa.Column('outbound_stops', sa.Integer(), nullable=True),
    sa.Column('inbound_stops', sa.Integer(), nullable=True),
    sa.Column('outbound_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('inbound_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('marketing_carriers', tco.db.base.JSONB(), nullable=False),
    sa.Column('flight_numbers', tco.db.base.JSONB(), nullable=False),
    sa.Column('cabin_class', sa.String(length=32), nullable=True),
    sa.Column('fare_family', sa.String(length=128), nullable=True),
    sa.Column('baggage_type', sa.String(length=16), nullable=False),
    sa.Column('baggage_raw', sa.String(length=255), nullable=True),
    sa.Column('refundability', sa.String(length=16), nullable=False),
    sa.Column('is_round_trip', sa.Boolean(), nullable=False),
    sa.Column('passenger_count', sa.Integer(), nullable=False),
    sa.Column('price_basis', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('offer_id')
    )
    op.create_table('rail_offers',
    sa.Column('offer_id', tco.db.base.GUID(length=36), nullable=False),
    sa.Column('origin_station_code', sa.String(length=16), nullable=True),
    sa.Column('destination_station_code', sa.String(length=16), nullable=True),
    sa.Column('origin_station_name', sa.String(length=255), nullable=True),
    sa.Column('destination_station_name', sa.String(length=255), nullable=True),
    sa.Column('origin_city_name', sa.String(length=128), nullable=True),
    sa.Column('destination_city_name', sa.String(length=128), nullable=True),
    sa.Column('outbound_train_number', sa.String(length=32), nullable=True),
    sa.Column('inbound_train_number', sa.String(length=32), nullable=True),
    sa.Column('outbound_departure_at', tco.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('outbound_arrival_at', tco.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('inbound_departure_at', tco.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('inbound_arrival_at', tco.db.base.TZDateTime(timezone=True), nullable=True),
    sa.Column('outbound_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('inbound_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('carriers', tco.db.base.JSONB(), nullable=False),
    sa.Column('car_type', sa.String(length=32), nullable=True),
    sa.Column('car_type_raw', sa.String(length=64), nullable=True),
    sa.Column('service_classes', tco.db.base.JSONB(), nullable=False),
    sa.Column('available_places_outbound', sa.Integer(), nullable=True),
    sa.Column('available_places_inbound', sa.Integer(), nullable=True),
    sa.Column('is_two_storey', sa.Boolean(), nullable=True),
    sa.Column('price_per_place_outbound', tco.db.base.Money(precision=14, scale=2), nullable=True),
    sa.Column('price_per_place_inbound', tco.db.base.Money(precision=14, scale=2), nullable=True),
    sa.Column('passenger_count', sa.Integer(), nullable=False),
    sa.Column('is_round_trip', sa.Boolean(), nullable=False),
    sa.Column('refundability', sa.String(length=16), nullable=False),
    sa.Column('segments', tco.db.base.JSONB(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('offer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rail_offers')
    op.drop_table('flight_offers')
    op.drop_index('ix_accommodation_property_key', table_name='accommodation_offers')
    op.drop_table('accommodation_offers')
    op.drop_index('ix_offers_snapshot_type', table_name='offers')
    op.drop_index('ix_offers_snapshot_source', table_name='offers')
    op.drop_index('ix_offers_fingerprint', table_name='offers')
    op.drop_index('ix_offers_equivalence', table_name='offers')
    op.drop_index('ix_offers_collected', table_name='offers')
    op.drop_table('offers')
    op.drop_index('ix_html_snapshots_snapshot', table_name='html_snapshots')
    op.drop_index('ix_html_snapshots_expires', table_name='html_snapshots')
    op.drop_index(op.f('ix_html_snapshots_collected_at'), table_name='html_snapshots')
    op.drop_table('html_snapshots')
    op.drop_index('ix_source_metrics_source_time', table_name='source_metrics')
    op.drop_index('ix_source_metrics_snapshot', table_name='source_metrics')
    op.drop_index(op.f('ix_source_metrics_observed_at'), table_name='source_metrics')
    op.drop_table('source_metrics')
    op.drop_index('ix_snapshot_source_results_snapshot', table_name='snapshot_source_results')
    op.drop_table('snapshot_source_results')
    op.drop_index(op.f('ix_scenario_runs_created_at'), table_name='scenario_runs')
    op.drop_index('ix_runs_status_type', table_name='scenario_runs')
    op.drop_index('ix_runs_snapshot', table_name='scenario_runs')
    op.drop_index('ix_runs_scenario_time', table_name='scenario_runs')
    op.drop_index('ix_runs_observation_date', table_name='scenario_runs')
    op.drop_index('ix_runs_cache_key', table_name='scenario_runs')
    op.drop_table('scenario_runs')
    op.drop_index('ix_raw_responses_source_time', table_name='raw_responses')
    op.drop_index('ix_raw_responses_snapshot', table_name='raw_responses')
    op.drop_index('ix_raw_responses_expires', table_name='raw_responses')
    op.drop_index(op.f('ix_raw_responses_collected_at'), table_name='raw_responses')
    op.drop_table('raw_responses')
    op.drop_index('ix_job_events_job_time', table_name='job_events')
    op.drop_table('job_events')
    op.drop_index('ix_exports_job', table_name='export_artifacts')
    op.drop_table('export_artifacts')
    op.drop_index('ix_snapshots_type_status', table_name='market_snapshots')
    op.drop_index('ix_snapshots_scenario_time', table_name='market_snapshots')
    op.drop_index('ix_snapshots_observation_date', table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_scenario_fingerprint'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_created_at'), table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_index('ix_jobs_status_type', table_name='jobs')
    op.drop_index('ix_jobs_scenario', table_name='jobs')
    op.drop_index('ix_jobs_parent', table_name='jobs')
    op.drop_index(op.f('ix_jobs_heartbeat_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_index('ix_jobs_created', table_name='jobs')
    op.drop_index(op.f('ix_jobs_correlation_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_celery_task_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_travel_scenarios_created_at'), table_name='travel_scenarios')
    op.drop_index('ix_scenarios_route', table_name='travel_scenarios')
    op.drop_index('ix_scenarios_fingerprint', table_name='travel_scenarios')
    op.drop_index('ix_scenarios_departure', table_name='travel_scenarios')
    op.drop_index('ix_scenarios_active_type', table_name='travel_scenarios')
    op.drop_table('travel_scenarios')
    op.drop_index('ix_source_confidence_source', table_name='source_confidence')
    op.drop_index(op.f('ix_source_confidence_created_at'), table_name='source_confidence')
    op.drop_table('source_confidence')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sources_created_at'), table_name='sources')
    op.drop_index('ix_sources_category_enabled', table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_scenario_templates_created_at'), table_name='scenario_templates')
    op.drop_table('scenario_templates')
    op.drop_index(op.f('ix_result_cache_scenario_fingerprint'), table_name='result_cache')
    op.drop_index('ix_result_cache_expires', table_name='result_cache')
    op.drop_index(op.f('ix_result_cache_created_at'), table_name='result_cache')
    op.drop_table('result_cache')
    op.drop_index(op.f('ix_cities_created_at'), table_name='cities')
    op.drop_index('ix_cities_active', table_name='cities')
    op.drop_table('cities')
    op.drop_index('ix_profiles_status', table_name='calculation_profiles')
    op.drop_index(op.f('ix_calculation_profiles_created_at'), table_name='calculation_profiles')
    op.drop_table('calculation_profiles')
    op.drop_index('ix_audit_time', table_name='audit_events')
    op.drop_index('ix_audit_object', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_index('ix_audit_actor', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
